apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-headless-service"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: master
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  - name: tcp-redis
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/component: master