apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: master
type: Opaque
data:
  redis-password: {{ .Values.secret.passwordKey | b64enc}}