apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-redis-service-configmap"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: master
data:
  REDIS_PORT: "6379"