{{- if .Values.master.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.master.serviceAccount.automountServiceAccountToken }}
metadata:
  name: "{{ .Values.name }}-serviceaccount"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: master
{{- end }}