postgresRootPassword: "mypass"

image: "postgres:15.9"


# Resource configuration
resources:
  requests:
    cpu: "500m"
    memory: "256M"
  limits:
    cpu: "1500m"
    memory: "1Gi"

diskSize: "10Gi"

updateStrategy:
  type: RollingUpdate

services: