# This is a basic workflow to help you get started with Actions



# Controls when the workflow will run
name: Workflow Work
 
on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed
  workflow_dispatch:
 
jobs:
  work:
    needs: dockerize
    env:
          image: ${{needs.dockerize.outputs.image}}
    name: Some Workflow Work
    runs-on: ubuntu-latest
    steps:
      - run: echo "Some work got triggered form ci"

