# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
env: 
  MATRIX: "{\"secret\":[\"ZS_DEVOPS_KEY\",\"PLATFORM_1_KEY\"]}"
jobs:
  
  list-account:
      runs-on: ubuntu-latest
      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
        - id: set-matrix
          run: echo "::set-output name=matrix::$MATRIX"
  setup-env:
    
    needs: list-account
    runs-on: ubuntu-latest
    outputs:
      file : ${{ steps.output-file.outputs.file }}
      secret: ${{ steps.output-secret.outputs.secret }}
      project: ${{ steps.output-project.outputs.project }}
      
    strategy:
      matrix: ${{fromJSON(needs.list-account.outputs.matrix)}} 
    
    env : 
      CHANGED_PROJECT: "platform-1"
    steps:
      - name: Setup Env
        run: |
          ORIGINAL_SECRET=${{ matrix.secret }}
          TRANSFORMED_SECRET=$(echo "$ORIGINAL_SECRET" | tr '[:upper:]' '[:lower:]' | sed -e 's/_key$//' -e 's/_/-/g')
          echo "PROJECT=$TRANSFORMED_SECRET" >> $GITHUB_ENV
          TRANSFORMED_SECRET="$TRANSFORMED_SECRET.json"
          echo "FILE_NAME=$TRANSFORMED_SECRET" >> $GITHUB_ENV
          echo "SECRET_NAME=${{ matrix.secret }}" >> $GITHUB_ENV
          
      - id: output-secret
        if: ${{ env.PROJECT == env.CHANGED_PROJECT }}
        run: 
          echo "::set-output name=secret::$SECRET_NAME"
      - id: output-project
        if: ${{ env.PROJECT == env.CHANGED_PROJECT }}
        run: 
          echo "::set-output name=project::$PROJECT"
      - id: output-file
        if: ${{ env.PROJECT == env.CHANGED_PROJECT }}
        run: 
          echo "::set-output name=file::$FILE_NAME"
  terragrunt:
      needs: setup-env
      runs-on: ubuntu-latest
      env: 
        PROJECT: ${{ needs.setup-env.outputs.project }}
        FILE_NAME: ${{ needs.setup-env.outputs.file }}
        SECRET_NAME: ${{ needs.setup-env.outputs.secret }}
      steps: 
        - name: Check env
          run: echo "${{env.SECRET_NAME}}"
          
 
