# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "development" branch
  push:
    branches: [ "development","staging" ]
  pull_request:
    branches: [ "development","staging" ]

  # Allows you to run this workflow manually from the Actions tab

jobs:

  setup-env:
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup Env
        if: contains(github.ref, "development")
        run: |
        
          echo "ENV_APP_NAME=DEV_APP_NAME" >> $GITHUB_ENV
          echo "ENV_GAR_PROJECT=DEV_GAR_PROJECT" >> $GITHUB_ENV
      - name: Setup Env
        if: contains(github.ref, "staging")
        run: |

          echo "ENV_APP_NAME=STAGE_APP_NAME" >> $GITHUB_ENV
          echo "ENV_GAR_PROJECT=STAGE_GAR_PROJECT" >> $GITHUB_ENV
      - name: export credentials file
        run: |
          echo "APP_NAME"
          echo '${{ vars[env.ENV_APP_NAME] }}' 
          echo "GAR PROJECT"
          echo '${{ vars[env.ENV_GAR_PROJECT }}'