# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
            app_name: sample-api
            GOPRIVATE: developer.zopsmart.com/go/gofr
            project_name: platform-379911
            cluster_name: headless-services-dev
            DB_NAME: ""
            DB_DIALECT: ""
            DB_USER: ""
            TRACER_URL: "https://tempo.observability-dev.gcpgap.zopsmart.com"
            TRACER_EXPORTER: "zipkin"
            minMemory: "512Mi"
            maxMemory: "1Gi"
            maxCPU: "1.5"
      
        
            
jobs:
  dockerize:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      image: ${{ steps.output-image.outputs.image }}
    steps:
      - id: output-image
        run: echo "image=`echo gcr.io/${{ env.project_name }}/${{ env.name }}:${{ github.sha }}`" >> "$GITHUB_OUTPUT"
    
  job2:
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - env:
          OUTPUT1: ${{needs.dockerize.outpus.image}}
        run: echo "$OUTPUT1"
