# This is a basic workflow to help you get started with Actions



# Controls when the workflow will run
name: Workflow Work
 
on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed
  workflow_dispatch:
 
jobs:
  work:
   
    name: Some Workflow Work
    runs-on: ubuntu-latest
    
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
      
      - run: echo "Some work got triggered form ci"

