# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  envir: ENV
jobs:
  
  loop:

    runs-on: ubuntu-latest
 
    outputs:
      image: ${{ steps.output-image.outputs.image }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for added_modified_file in ${{ steps.files.outputs.all }}; do
            echo ${added_modified_file}
          done
          
      - name: List GCP Folders
        id: list_folders
        run: |
          # List folders in your GCP directory and store them in a variable
          FOLDER_NAMES=$(gsutil ls gs://your-gcp-bucket/path/to/directory/)

          # Replace hyphens with underscores and suffix _KEY to each folder name
          FOLDER_NAMES_UNDERSCORED=$(echo "$FOLDER_NAMES" | sed 's|-|_|g' | sed 's|gs://your-gcp-bucket/||' | sed 's|/|_KEY\n|g')

          # Convert the folders to a matrix format
          FOLDER_MATRIX=$(echo "$FOLDER_NAMES_UNDERSCORED" | awk '{print "folder_name=" $1}')

          # Export the matrix as an environment variable
          echo "$FOLDER_MATRIX" >> $GITHUB_ENV

      - name: Echo Secrets

        run: |
          # Read the folder names from the matrix and create environment variables for secrets
          while IFS= read -r folder_var; do
            eval "$folder_var"
            secret_name=$(echo "$folder_name" | sed 's/_/-/g')

            # Access the secret value and set it as an environment variable
            secret_value=$(gcloud secrets versions access latest --secret="$folder_name")
            echo "export $secret_name=$secret_value" >> $GITHUB_ENV
          done <<< "$folder_matrix"

          # Source the environment variables to make them available
          source $GITHUB_ENV
