# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  
  job1:
    runs-on: ubuntu-latest
    outputs:
			# This needs to match your step's id and name parameters
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
			# Important: Do not forget the id!
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"secret\":[\"ZS_DEVOPS_KEY\", \"PLATFORM_1_KEY\"]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
			# This needs to match the first job's name and output parameter
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
    
    steps:
      - name: Setup Env
        run: |
          echo "SECRET_NAME=${{ matrix.node }}" >> $GITHUB_ENV
      - name: Run a multi-line script
        run: |
          echo "SECRET_NAME=$secret_name" >> $GITHUB_ENV
          echo "SECRET_NAME = $SECRET_NAME"
          echo "SECRET_NAME = ${{ env.SECRET_NAME }}"
          SECRET_VALUE=${{ secrets[env.SECRET_NAME] }}
          echo "SECRET_VALUE = $SECRET_VALUE"
          
 
