# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  envir: ENV
jobs:
  
  loop:

    runs-on: ubuntu-latest
 
    outputs:
      image: ${{ steps.output-image.outputs.image }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for added_modified_file in ${{ steps.files.outputs.all }}; do
            echo ${added_modified_file}
          done
          
      - name: List GCP Folders
        id: list_folders
        run: |
          # List folder names in the "gcp" directory and store them in a variable
          FOLDER_NAMES=$(ls gcp/)

          # Process folder names to replace hyphens with underscores and add suffix _KEY
          FOLDER_NAMES_UNDERSCORED=$(echo "$FOLDER_NAMES" | sed 's|-|_|g' | sed 's|.*|&_KEY|')

          # Convert the folders to a matrix format and export it as an environment variable
          FOLDER_MATRIX=$(echo "$FOLDER_NAMES_UNDERSCORED" | awk '{print "folder_name=" $1}')
          echo "$FOLDER_MATRIX" >> $GITHUB_ENV

      - name: Echo Secrets for Folders
        run: |
          # Read the folder names from the matrix and create environment variables for secrets
          while IFS= read -r folder_var; do
            eval "$folder_var"
            secret_name=$(echo "$folder_name" | sed 's/_/-/g')

            # Access the GitHub secret value and set it as an environment variable
            secret_value="${{ secrets[secret_name] }}"
            echo "echo ::set-env name=$folder_name::$secret_value"
          done <<< "$folder_matrix"
