# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
            
jobs:
  loop:

    runs-on: ubuntu-latest
 
    outputs:
      image: ${{ steps.output-image.outputs.image }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for added_modified_file in ${{ steps.files.outputs.all }}; do
            echo ${added_modified_file}
          done
          
      - id: sort
        run: | 
          readarray -td $'\0' sorted < <(
                    for i in ${{ steps.files.outputs.all }};
                    do     printf '%s %s\0' "${#i}" "$i";
                    done |
                            sort -bz -k1,1n -k2|
                            cut -zd " " -f2-
                    )

          printf '%s\n' "${sorted[@]}"
          echo "files=`echo ${sorted[@]}`" >> "$GITHUB_OUTPUT"
      - name: echo files
        run: echo ${{ steps.sort.outputs.files }}

      - name: loop over 
        run: |
          ls
          for added_modified_file in ${{ steps.sort.outputs.files }}; do
            echo ${added_modified_file}
            ls
            cd $(dirname ${added_modified_file})
          done
