name: Helm Deployment

on:
  push:
    branches: [ main ]
env:
  project_name: "zopsmart-test"
  cluster_name: "test-pvc-stage"
  region: "us-central1"
jobs:
  Helm_Charts:
    name: "Helm Deployment"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            nginx:
              - 'cluster-configs/nginx.yaml'
            fluent:
              - 'cluster-configs/fluent-bit.yaml'
            cert-manager:
              - 'cluster-configs/cert-manager.yaml'
            issuer:
              - 'cluster-configs/issuer.yaml'

        # run only if some file in 'src' folder was changed

      - if: steps.changes.outputs.fluent == 'true'
        run: |
          echo true
      - if: steps.changes.outputs.cert-manager == 'true'
        run: |
          echo true
      - if: steps.changes.outputs.nginx == 'true'
        run: |
          echo true
      - if: steps.changes.outputs.issuer == 'true'
        run: |
          echo true
