# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  envir: ENV
jobs:
  
  loop:

    runs-on: ubuntu-latest
 
    outputs:
      image: ${{ steps.output-image.outputs.image }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for added_modified_file in ${{ steps.files.outputs.all }}; do
            echo ${added_modified_file}
          done
          
      - name: List GCP Folders
        id: list_folders
        run: |
          # List folder names in the "gcp" directory and store them in an array
          IFS=$'\n' read -d '' -r -a FOLDER_NAMES <<< "$(ls gcp/)"

          # Process folder names to replace hyphens with underscores and add suffix _KEY
          FOLDER_NAMES_UNDERSCORED=()
          for folder in "${FOLDER_NAMES[@]}"; do
            folder_name=$(echo "$folder" | sed 's|-|_|g')
            FOLDER_NAMES_UNDERSCORED+=("${folder_name}_KEY")
          done

          # Export the array as an environment variable
          export FOLDER_NAMES_UNDERSCORED
      - name: Echo Secrets for Folders
        run: |
          # Read the folder names from the matrix and set secret_name as an environment variable
          for folder_name in "${FOLDER_NAMES_UNDERSCORED[@]}"; do
            eval "$folder_var"
            secret_name=$(echo "$folder_name" | sed 's/_/-/g')
            echo $secret_name
            echo "SECRET_NAME=$secret_name" >> $GITHUB_ENV
            # Access the GitHub secret value using the environment variable and echo it
            secret_value="${{ secrets[env.SECRET_NAME] }}"
            echo "Secret for $SECRET_NAME (Secret name: $secret_value): $secret_value"
          done 
          
 
