name: Build and Push Base Images

on:
  push:
    branch: "development"


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: zopsmart/gha-images

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:

  changed-files:
    outputs:
      files: ${{ steps.files.outputs.all }}
      version: ${{ steps.version.out.version }}
    runs-on: ubuntu-latest

    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for added_modified_file in ${{ steps.files.outputs.all }}; do
            echo ${added_modified_file}
          done
      - id: version
        run: |
          echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

  build-and-push-deployment-image:
    needs: changed-files
    if: ${{ contains(needs.changed-files.outputs.files, 'deployments/') }}

    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      #
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.



      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: deployments/.
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:deployments-${{ needs.changed-files.outputs.version}}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-go-image:
    needs: changed-files
    if: ${{ contains(needs.changed-files.outputs.files, 'go/') }}

    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      #
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
