name: helm-test

on:
  push:
    branches: [ development ]

env:
  PROJECT_NAME: hello
  CLUSTER_NAME: products-1


jobs:
  Deployment:
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'

    name: "Deployment"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            helm1:
              - 'deployments/helm1.yaml'
            helm2:
              - 'deployments/helm2.yaml'
            helm3:
              - 'deployments/helm3.yaml'
            helm4:
              - 'deployments/helm4.yaml'
            helm4:
              - 'deployments/helm5.yaml'
      - name: helm1
        if: steps.nginx.outputs.heml1 == 'true'
        run: cat deployments/helm1.yaml
      - name: helm2
        if: steps.nginx.outputs.heml2 == 'true'
        run: cat deployments/helm2.yaml
      - name: helm3
        if: steps.nginx.outputs.heml3 == 'true'
        run: cat deployments/helm3.yaml
      - name: helm4
        if: steps.nginx.outputs.heml4 == 'true'
        run: cat deployments/helm4.yaml
      - name: helm5
        if: steps.nginx.outputs.heml5 == 'true'
        run: cat deployments/helm5.yaml

