name: Deployments

on:
  push:
    branches: [ development ]

env:
  PROJECT_NAME: hello
  CLUSTER_NAME: products-1


jobs:
  Deployment:
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'

    name: "Deployment"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
        id: go
      # List of files that are added or modified in the commit
      - name: SET CONFIG
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development'}}
        run: |
          touch README.md
          git config --global user.email "action@github.com" && git config --global user.name "GitHub-Action"
          git config --global --add safe.directory /__w/$(basename ${{ github.repository }})/$(basename ${{ github.repository }})
          git diff --quiet --exit-code README.md || git commit README.md -m "updating coverage in README.md"
      - name: Push Coverage Badge
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development'}}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{github.ref}}

      - id: output-sha
        run: |
          if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == 'refs/heads/development' ]]; then
            sha=$(git rev-parse HEAD)
          fi
          echo "$sha"
          echo "sha=$sha" >> "$GITHUB_OUTPUT"
