name: Build and Deploy for Go service

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

env:
  APP_NAME: test-serv
  NAMESPACE: test-app
  CLUSTER_NAME: test-prod-2105
  CLUSTER_PROJECT: quick-flame-421806
  GAR_PROJECT: quick-flame-421806
  GAR_REGISTRY: kops-dev

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: 🚀 test azure login

    steps:
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}